name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Setup Node.js for npm
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Determine npm tag
        id: npm-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" =~ (alpha|beta|rc|next|canary) ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
          echo "Publishing version $VERSION with tag: $(cat $GITHUB_OUTPUT | grep tag | cut -d= -f2)"

      - name: Publish to npm
        run: npm publish --access public --tag ${{ steps.npm-tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
