name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Verify bundle size
        run: |
          GZIP_SIZE=$(gzip -c dist/esm/index.js | wc -c)
          if [ $GZIP_SIZE -gt 2150 ]; then
            echo "❌ Bundle size exceeds ~2KB gzipped limit!"
            exit 1
          fi
          echo "✅ Bundle size: $GZIP_SIZE bytes (within ~2KB limit)"

      - name: Setup Node.js for npm
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}