name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Type check
        run: bun run typecheck

      - name: Run tests
        run: bun run test

      - name: Run tests with coverage
        run: bun run test:coverage

      - name: Build project
        run: bun run build

      - name: Check bundle size
        run: |
          ESM_SIZE=$(stat -f%z dist/esm/index.js 2>/dev/null || stat -c%s dist/esm/index.js)
          GZIP_SIZE=$(gzip -c dist/esm/index.js | wc -c)
          echo "ESM size: $ESM_SIZE bytes"
          echo "Gzipped: $GZIP_SIZE bytes"
          if [ $GZIP_SIZE -gt 2150 ]; then
            echo "❌ Bundle size exceeds ~2KB gzipped limit!"
            exit 1
          else
            echo "✅ Bundle size within ~2KB limit ($GZIP_SIZE bytes)"
          fi

      - name: Upload coverage to Codecov
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false